### ISSUE TITLE
Issue #49 still appears

### ISSUE THREAD

**Issue by ghost** [CreativeMD/PlayerRevive#52]
All in a title. I used same config.

Here it is, if you need
https://pastebin.com/1akPbFRF

**Comment by CreativeMD** [comment]
Removed the death.attack because they are not part of the name itself. List of available damage types (vanilla):
inFire
lightningBolt
onFire
lava
hotFloor
inWall
cramming
drown
starve
cactus
fall
flyIntoWall
outOfWorld
generic
magic
wither
anvil
fallingBlock
dragonBreath
fireworks
mob
player
arrow
thrown
indirectMagic
thorns
explosion.player
explosion
