### ISSUE TITLE
Still dying

### ISSUE THREAD

**Issue by Nilsoon** [CreativeMD/PlayerRevive#85]
Hello! I have a server in version 1.16.5 with the player revive mod, and I have a problem that I can't fix.
When someone dies, and stays bleeding on the ground, and surrenders (holds for 4 seconds), when it reappears, without touching anything, it can move for a few seconds, but soon after it dies again for no reason.
[Video of the bug](https://medal.tv/games/minecraft/clips/iDVHDKi5I3EOZ/d1337iLtmmj7?invite=cr-MSxIN2csMTU5MDgzNzIs)

**Comment by CreativeMD** [comment]
Hey, sorry for not responding earlier. I got no idea why this issue occurs. But unfortunately I have dropped support for 1.16.5 some time ago. It's probably caused by another mod, because it works fine with just PlayerRevive installed (at least that's what I have been told). You could remove a few mods to find the cause. I highly recommend to update to 1.18. If the issue still occurs there I can attempt to fix it.
